# -*- restclient -*-
:addr = http://127.0.0.1:8000
:key = f340600cd80455ead9b0982d9c8b7d71db0b03df

# login
POST :addr/rest-auth/login/
Content-Type: application/json
{
	"username": "admin",
	"password": "adminpass1"
}

# POST new app
POST :addr/app/
Content-Type: application/json
Authorization: Token :key
{
	"name": "emacs"
}

# GET app info
GET :addr/app/emacs/

# GET user
GET :addr/user/admin/

# link app to user
POST :addr/user/
Content-Type: application/json
Authorization: Token :key
"emacs"

# update user's app metadata
PUT :addr/user/app/emacs/
Authorization: Token :key
Content-Type: application/json
{
	"notes": "pozdrawiam"
}

# start new app session
POST :addr/user/app/emacs/
Authorization: Token :key
Content-Type: application/json
{
	"start_time": "2017-05-31T22:50:00"
}


# get avail sessions
GET :addr/user/app/emacs/session/
Authorization: Token :key

# session heartbeat
PUT :addr/user/app/emacs/session/
Authorization: Token :key
Content-Type: application/json
{
	"end_time": "2017-05-31T23:00:10"
}

# session end
DELETE :addr/user/app/emacs/session/
Authorization: Token :key
