# -*- restclient -*-
:addr = http://127.0.0.1:8000
:key = 09b69c7e7497beaab8ed1abf145da2761a151191

# login
POST :addr/rest-auth/login/
Content-Type: application/json
{
	"username": "admin",
	"password": "adminpass1"
}

# POST new app
POST :addr/app/
Content-Type: application/json
Authorization: Token :key
{
	"name": "emacs"
}

# GET app info
GET :addr/app/emacs/

# GET user
GET :addr/user/admin1/

# link app to user
POST :addr/user/
Content-Type: application/json
Authorization: Token :key
"emacs"

# update user's app metadata
PUT :addr/user/app/emacs/
Authorization: Token :key
Content-Type: application/json
{
	"notes": "pozdrawiam"
}

# start new app session
POST :addr/user/app/emacs/
Authorization: Token :key
