# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 23:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_auto_20170530_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
