# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endpoints', '0005_auto_20170530_2356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usedapp',
            unique_together=set([('user', 'app')]),
        ),
    ]
