# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_auto_20170531_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedapp',
            name='current_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='endpoints.AppSession'),
        ),
    ]
