# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0007_usedapp_current_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsession',
            name='duration',
        ),
        migrations.AddField(
            model_name='appsession',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appsession',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
